DROP TABLE IF EXISTS `ps_themeconfigurator`;
CREATE TABLE `ps_themeconfigurator` (
  `id_item` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `id_shop` int(10) unsigned NOT NULL,
  `id_lang` int(10) unsigned NOT NULL,
  `item_order` int(10) unsigned NOT NULL,
  `title` varchar(100) DEFAULT NULL,
  `title_use` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `hook` varchar(100) DEFAULT NULL,
  `url` text,
  `target` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `image` varchar(100) DEFAULT NULL,
  `image_w` varchar(10) DEFAULT NULL,
  `image_h` varchar(10) DEFAULT NULL,
  `html` text,
  `active` tinyint(1) unsigned NOT NULL DEFAULT '1',
  PRIMARY KEY (`id_item`)
) ENGINE=InnoDB AUTO_INCREMENT=38 DEFAULT CHARSET=utf8;

/* Scheme for table ps_themeconfigurator */
INSERT INTO `ps_themeconfigurator` VALUES
('8','1','1','1',NULL,'0','home','index.php?id_category=13&controller=category','0',NULL,NULL,NULL,'<div class=\"material-design-ico icon\">  </div>\r\n<h2>Free Shipping on orders over $99</h2>\r\n<p>Lorem ipsum dolor sit amet conse ctetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>','1'),
('9','1','2','1',NULL,'0','home','index.php?id_category=13&controller=category','0',NULL,NULL,NULL,'<div class=\"material-design-ico icon\">  </div>\r\n<h2>Free Shipping on orders over $99</h2>\r\n<p>Lorem ipsum dolor sit amet conse ctetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>','1'),
('10','1','3','1',NULL,'0','home','index.php?id_category=13&controller=category','0',NULL,NULL,NULL,'<div class=\"material-design-ico icon\">  </div>\r\n<h2>Free Shipping on orders over $99</h2>\r\n<p>Lorem ipsum dolor sit amet conse ctetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>','1'),
('11','1','4','1',NULL,'0','home','index.php?id_category=13&controller=category','0',NULL,NULL,NULL,'<div class=\"material-design-ico icon\">  </div>\r\n<h2>Free Shipping on orders over $99</h2>\r\n<p>Lorem ipsum dolor sit amet conse ctetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>','1'),
('12','1','5','1',NULL,'0','home','index.php?id_category=13&controller=category','0',NULL,NULL,NULL,'<div class=\"material-design-ico icon\">  </div>\r\n<h2>Free Shipping on orders over $99</h2>\r\n<p>Lorem ipsum dolor sit amet conse ctetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>','1'),
('13','1','1','2',NULL,'0','home','index.php?id_category=14&controller=category','0',NULL,NULL,NULL,'<div class=\"material-design-ico icon\">  </div>\r\n<h2>Order return. Returns within 14 days</h2>\r\n<p>Lorem ipsum dolor sit amet conse ctetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>','1'),
('14','1','2','2',NULL,'0','home','index.php?id_category=14&controller=category','0',NULL,NULL,NULL,'<div class=\"material-design-ico icon\">  </div>\r\n<h2>Order return. Returns within 14 days</h2>\r\n<p>Lorem ipsum dolor sit amet conse ctetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>','1'),
('15','1','3','2',NULL,'0','home','index.php?id_category=14&controller=category','0',NULL,NULL,NULL,'<div class=\"material-design-ico icon\">  </div>\r\n<h2>Order return. Returns within 14 days</h2>\r\n<p>Lorem ipsum dolor sit amet conse ctetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>','1'),
('16','1','4','2',NULL,'0','home','index.php?id_category=14&controller=category','0',NULL,NULL,NULL,'<div class=\"material-design-ico icon\">  </div>\r\n<h2>Order return. Returns within 14 days</h2>\r\n<p>Lorem ipsum dolor sit amet conse ctetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>','1'),
('17','1','5','2',NULL,'0','home','index.php?id_category=14&controller=category','0',NULL,NULL,NULL,'<div class=\"material-design-ico icon\">  </div>\r\n<h2>Order return. Returns within 14 days</h2>\r\n<p>Lorem ipsum dolor sit amet conse ctetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>','1'),
('18','1','1','3',NULL,'0','home','index.php?id_category=15&controller=category','0',NULL,NULL,NULL,'<div class=\"material-design-ico icon\">  </div>\r\n<h2>COD. Cash on delivery</h2>\r\n<p>Lorem ipsum dolor sit amet conse ctetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>','1'),
('19','1','2','3',NULL,'0','home','index.php?id_category=15&controller=category','0',NULL,NULL,NULL,'<div class=\"material-design-ico icon\">  </div>\r\n<h2>COD. Cash on delivery</h2>\r\n<p>Lorem ipsum dolor sit amet conse ctetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>','1'),
('20','1','3','3',NULL,'0','home','index.php?id_category=15&controller=category','0',NULL,NULL,NULL,'<div class=\"material-design-ico icon\">  </div>\r\n<h2>COD. Cash on delivery</h2>\r\n<p>Lorem ipsum dolor sit amet conse ctetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>','1'),
('21','1','4','3',NULL,'0','home','index.php?id_category=15&controller=category','0',NULL,NULL,NULL,'<div class=\"material-design-ico icon\">  </div>\r\n<h2>COD. Cash on delivery</h2>\r\n<p>Lorem ipsum dolor sit amet conse ctetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>','1'),
('22','1','5','3',NULL,'0','home','index.php?id_category=15&controller=category','0',NULL,NULL,NULL,'<div class=\"material-design-ico icon\">  </div>\r\n<h2>COD. Cash on delivery</h2>\r\n<p>Lorem ipsum dolor sit amet conse ctetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>','1'),
('23','1','1','1',NULL,'0','top','index.php?id_category=13&controller=category','0','767283c2539a1f23b6f9f27105a9081749b56706_banner1.jpg','370','191','<h3>Sneakers</h3>\r\n<h4>50% off</h4>','1'),
('24','1','2','1',NULL,'0','top','index.php?id_category=13&controller=category','0','63cb6684040e7ead90816cef7f5127fc7ff02052_banner1.jpg','370','191','<h3>Sneakers</h3>\r\n<h4>50% off</h4>','1'),
('25','1','3','1',NULL,'0','top','index.php?id_category=13&controller=category','0','2687eb7c3078fcf6eca932ce013db8955dbbf66d_banner1.jpg','370','191','<h3>Sneakers</h3>\r\n<h4>50% off</h4>','1'),
('26','1','4','1',NULL,'0','top','index.php?id_category=13&controller=category','0','f24fd2bbc3933b7d01774cc973223906f981a9ae_banner1.jpg','370','191','<h3>Sneakers</h3>\r\n<h4>50% off</h4>','1'),
('27','1','5','1',NULL,'0','top','index.php?id_category=13&controller=category','0','8bebb294abeee652eec2f409b88d44407643d532_banner1.jpg','370','191','<h3>Sneakers</h3>\r\n<h4>50% off</h4>','1'),
('28','1','1','2',NULL,'0','top','index.php?id_category=14&controller=category','0','2900e2e34b0175ba7e2fe75ec455e91c529b5387_banner2.jpg','370','191','<h3>Buy 1 get 1</h3>\r\n<h4>20% off</h4>','1'),
('29','1','2','2',NULL,'0','top','index.php?id_category=14&controller=category','0','d64f6bfaa06b4388318b7f516bd429e227ece688_banner2.jpg','370','191','<h3>Buy 1 get 1</h3>\r\n<h4>20% off</h4>','1'),
('30','1','3','2',NULL,'0','top','index.php?id_category=14&controller=category','0','00dcdfed4f17ffa24a97d040128d7e5973d4a275_banner2.jpg','370','191','<h3>Buy 1 get 1</h3>\r\n<h4>20% off</h4>','1'),
('31','1','4','2',NULL,'0','top','index.php?id_category=14&controller=category','0','95b5680c271c8023682c5deea11456af794c5795_banner2.jpg','370','191','<h3>Buy 1 get 1</h3>\r\n<h4>20% off</h4>','1'),
('32','1','5','2',NULL,'0','top','index.php?id_category=14&controller=category','0','e9a16217f86e552f79a9a580f2a4ad68d512bcc1_banner2.jpg','370','191','<h3>Buy 1 get 1</h3>\r\n<h4>20% off</h4>','1'),
('33','1','1','3',NULL,'0','top','index.php?id_category=15&controller=category','0',NULL,NULL,NULL,'<h2>70%off</h2>\r\n<button>Shop now!</button>','1'),
('34','1','2','3',NULL,'0','top','index.php?id_category=15&controller=category','0',NULL,NULL,NULL,'<h2>70%off</h2>\r\n<button>Shop now!</button>','1'),
('35','1','3','3',NULL,'0','top','index.php?id_category=15&controller=category','0',NULL,NULL,NULL,'<h2>70%off</h2>\r\n<button>Shop now!</button>','1'),
('36','1','4','3',NULL,'0','top','index.php?id_category=15&controller=category','0',NULL,'0','0','<h2>70%off</h2>\r\n<button>Shop now!</button>','1'),
('37','1','5','3',NULL,'0','top','index.php?id_category=15&controller=category','0',NULL,NULL,NULL,'<h2>70%off</h2>\r\n<button>Shop now!</button>','1');
